version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATA_DIR=/data
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - rnpksync-data:/data
    restart: unless-stopped

volumes:
  rnpksync-data: